apiVersion: v1
kind: Service
metadata:
  name: {{.Questions.appName}}
  namespace: {{.Questions.env}}
  labels:
    app: {{.Questions.appName}}
    env: {{.Questions.env}}
spec:
  selector:
    app: {{.Questions.appName}}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP