# Configuration file for cache-config
name: cache-config
environment: development
target: dev-region-2

# Application settings
app:
  name: cache-config
  version: "1.0.0"
  debug: true

# Database configuration
database:
  host: cache-config-db.development.local
  port: 5432
  name: cache-config_development
  ssl: disable

# Service configuration
service:
  port: 8080
  timeout: 30s
  max_connections: 100

# Logging
logging:
  level: debug
  format: json
  output: stdout