output:
  base_path: "{{.Questions.environment}}/{{.Questions.target}}/{{.Questions.name}}"

files:
  server-config.yaml:
    filename: "{{.Questions.name}}-server.yaml"
  database-config.yaml:
    filename: "{{.Questions.name}}-database.yaml"
  api-spec.yaml:
    filename: "{{.Questions.name}}-api.yaml"
  monitoring-config.yaml:
    filename: "{{.Questions.name}}-monitoring.yaml"