templates:
  web-service:
    type: directory
    path: web-service
  configuration:
    type: file
    path: configuration.yaml
  batch-job:
    type: file
    path: batch-job.yaml

questions:
  template_question: templateType
  order:
    - templateType
    - name
    - environment
    - target
  definitions:
    templateType:
      prompt: 'What type of template do you want to use?'
      choices:
        - web-service
        - configuration
        - batch-job
    name:
      prompt: 'What is the name of your item?'
      type:
        dynamic:
          dependency_questions: ['templateType']
        interactive: true
      choices:
        web-service:
          - user-service
          - payment-api
          - notification-service
        configuration:
          - database-config
          - cache-config
          - logging-config
          - monitoring-config
          - security-config
        batch-job:
          - data-processor
          - report-generator
          - cleanup-task
          - backup-job
          - analytics-job
    environment:
      prompt: 'Which environment do you want to target?'
      choices:
        - development
        - staging
        - production
    target:
      prompt: 'Which target destinations do you want to deploy to?'
      type:
        multiple: true
        dynamic:
          dependency_questions: ['environment']
      choices:
        development:
          - dev-region-1
          - dev-region-2
          - dev-region-3
        staging:
          - staging-region-1
          - staging-region-2
          - staging-region-3
        production:
          - prod-region-1
          - prod-region-2
