name: Claude Review - Specific Authors

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-by-author:
    # Only run for PRs from specific authors
    if: |
      github.event.pull_request.user.login == 'daylight55'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Review PR from Specific Author
        uses: daylight55/claude-code-action@main
        with:
          use_oauth: true
          model: 'claude-sonnet-4-20250514'
          claude_access_token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          claude_refresh_token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          claude_expires_at: ${{ secrets.CLAUDE_EXPIRES_AT }}
          timeout_minutes: '60'
          direct_prompt: |
            あなたはレビュワーです。
            追加差分コメントについて指摘事項がないか確認してください。
            もし指摘事項があれば、PRの差分にコメントしてください。
            例: @claude xxx
